
import { Fredoka } from 'next/font/google'
import FeedPage from './feed/page'
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter} from "next/font/google";
import "./globals.css";
import DottedBg from "@/components/ui/dotted-bg";
import PathnameWarpper from "@/components/PathnameWarpper";
// Instantiate Geist
const geistSans = Geist({ 
  subsets: ['latin'],
  variable: '--font-geist-sans',
});

const fredoka = Fredoka({
  subsets: ['latin'],
  weight: ['600'],
  variable: '--font-fredoka',
})

// Instantiate Geist Mono
const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fredoka.className} antialiased dotted-bg`}
      > 
        <PathnameWarpper>
          {children}
        </PathnameWarpper>
        {/* Add CSS for dotted background */}
        <DottedBg />
      </body>
    </html>
  );
}
